version: "3.4"
services:
  postgres:
    container_name: postgres_container
    image: postgres:13.3
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "django_db_drf"
      POSTGRES_USER: "django_user_drf"
      POSTGRES_PASSWORD: "django_password_drf"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "32700:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user_drf -d django_db_drf"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres
  redis:
    container_name: redis_container
    image: redis
    command: redis-server
    ports:
      - "14000:6379"
    restart: unless-stopped
    networks:
      - postgres
  wkhtmltopdf:
    container_name: wkhtmltopdf-aas
    image: "openlabs/docker-wkhtmltopdf-aas"
    ports:
      - "4133:80"
    restart: unless-stopped
    networks:
      - postgres
networks:
  postgres:
    driver: bridge