# Generated by Django 4.1.2 on 2022-10-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'new'), ('2', 'rendered'), ('3', 'printed')], default='new', max_length=15, null=True, verbose_name='Status check'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='check_type',
            field=models.CharField(blank=True, choices=[('1', 'kitchen'), ('2', 'client')], max_length=15, null=True, verbose_name='Type check'),
        ),
    ]
