# Generated by Django 4.1.2 on 2022-10-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_alter_check_status_alter_printer_check_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'kitchen'), ('2', 'client')], max_length=512, null=True, verbose_name='Type check'),
        ),
    ]
