# Generated by Django 4.1.2 on 2022-10-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_alter_check_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('rendered', 'rendered'), ('printed', 'printed')], default='new', max_length=15, null=True, verbose_name='Status check'),
        ),
        migrations.AlterField(
            model_name='check',
            name='type',
            field=models.CharField(blank=True, choices=[('kitchen', 'kitchen'), ('client', 'client')], max_length=512, null=True, verbose_name='Type check'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='check_type',
            field=models.CharField(blank=True, choices=[('kitchen', 'kitchen'), ('client', 'client')], max_length=15, null=True, verbose_name='Type check'),
        ),
    ]
