# Generated by Django 4.1.2 on 2022-10-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0004_alter_check_status_alter_check_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='api_key',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Key access API'),
        ),
    ]
