# Generated by Django 4.1.2 on 2022-10-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0006_rename_printer_id_check_printer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='printer',
            new_name='printer_id',
        ),
    ]
