# Generated by Django 4.1.2 on 2022-10-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0007_rename_printer_check_printer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='printer_id',
            new_name='printer',
        ),
    ]
