# Generated by Django 4.1.2 on 2022-10-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0008_rename_printer_id_check_printer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='api_key',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True, verbose_name='Key access API'),
        ),
    ]
